name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Gradle help
        run: gradle --help
      - name: Gradle init Android
        if: false
        run: |
          mkdir project && cd project
          gradle init --type java-application
      - name: List project
        run: find project -type f
      - name: List files
        if: false
        run: find -type f -name "*.gradle" -exec cat {} \;
      - name: Build
        run: cd project && gradle build
      - name: List build
        run: find project -type f -name "*.apk"
      - uses: actions/upload-artifact@v3
        with:
          name: my-apk
          path: project/app/build/outputs/apk/debug/app-debug.apk
