name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Gradle help
        run: gradle --help
      - name: Gradle init Android
        run: |
          mkdir project && cd project
          gradle init --type java-application
      - name: List project
        run: find project -type f
      - name: List files
        run: find -type f -name "*.gradle" -exec cat {} \;
